server:
  # 端口
  port: 8160

spring:
  # 时区配置
  jackson:
    date-format: yyyy-MM-dd HH:m m:ss
    time-zone: GMT+8

  application:
    # 服务名
    name: service-ucenter
  # redis相关配置
  redis:
    host: 172.16.88.168
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 # 最大阻塞等待时间（负数表示没有限制）
        max-idle: 5
        min-idle: 0

  # 配置数据源
  datasource:
    username: root
    password: tokyo302
    url: jdbc:mysql://localhost:3306/guli_project?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务端口号

mybatis-plus:
  configuration:
    # sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/tsuiraku/educenter/mapper/**/*.xml


# 微信开发平台
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback # 重定向url

feign:
  httpclient:
    enabled: true # 开启熔断机制